version: '3'
services:
  handson-webapp:
    build:
      context: ./handson-webapp
      args:
        BUILD_TAG: 3.7
    container_name: handson-webapp
    image: handson-webapp:1.0
    command: python manage.py runserver --nothreading 0.0.0.0:8000
    environment:
      - WORK_DIR=/home/handson-webapp
      - HOME=/home/handson-webapp
      - DISPLAY
      - TZ=Asia/Tokyo
    hostname: handson-webapp
    ports:
        - 8000:8000
    depends_on:
      - redis
    links:
      - redis:redis

  redis:
    image: redis:6.0.9

  celery:
    build:
      context: ./handson-webapp
      args:
        BUILD_TAG: 3.7
    container_name: handson-backend
    image: handson-backend:1.0
    command: celery -A nodeai_app worker --concurrency=1 -l info
    environment:
      - WORK_DIR=/home/handson-webapp
      - HOME=/home/handson-webapp
      - DISPLAY
      - TZ=Asia/Tokyo
    hostname: handson-webapp
    depends_on:
      - redis
    links:
      - redis:redis
